### ISSUE TITLE
 you can make all the images of chapter displayed on the one page ? please

### ISSUE THREAD

**Issue by Mangavj** [fbg13/Clarity-Manga-Reader#4]
you can make all the images of chapter displayed on the one page ? please
Thank

**Comment by f-b-g-m** [comment]
Sorry but i can't.
I tried to do it, but i forgot how it works to be honest (bad code structure too), and figuring it out is just not worth it.

I'm working on a new reader, not on wordpress though, and it's almost finished. Will have a link in the main page when it's done if you're interested.

**Comment by kosao** [comment]
@f-b-g-m What platform will this new manga reader be for?  I'm excited to see what it's like!

**Comment by f-b-g-m** [comment]
http://processwire.com
